.travis.yml
README.md
ibm_platform_services/__init__.py
ibm_platform_services/global_search_v2.py
ibm_platform_services/global_tagging_v1.py
test/integration/test_global_search_v2.py
test/integration/test_global_tagging_v1.py
test/unit/test_global_search_v2.py
test/unit/test_global_tagging_v1.py

This PR adds the global-search and global-tagging services to the project
**Fixes:** n/a

Add services to project

---

.travis.yml
setup.py

Adds pypi deployment to the travis build
**Fixes:** n/a

fix: add pypi deployment to build

---

requirements.txt
test/unit/test_global_search_v2.py
test/unit/test_global_tagging_v1.py

This PR contains changes a re-gen of the unit tests for the existing services in the project (search, tagging) to leverage the improvements made to the Python generator's unit test code.
I also updated the project's dependency on the python core to be 2.0.0 (the current latest).
**Fixes:** n/a

chore: re-gen services for new unit test code

---

ibm_platform_services/__init__.py
ibm_platform_services/common.py
test/integration/test_iam_access_groups_v2.py

This PR corrects an oversight where the IamAccessGroupsV2 class was not being included in the package's __init__.py filie.
**Fixes:** n/a

fix(IAM Access Groups): add import to __init__.py

---

test/integration/test_iam_access_groups_v2.py

Temporarily updates one of the IAM Access Groups tests to succeed during intermittent failures.
**Fixes:** One step as part of fixing this issue: https://github.ibm.com/IAM/uum/issues/2348
Temporary testing change
Temporary testing change

test(IAM Access Groups): Temporarily patched a test that intermittently fails

---

test/integration/test_iam_access_groups_v2.py

Follow up bug fix to temporary changes made in this pr: https://github.com/IBM/platform-services-python-sdk/pull/12
**Fixes:** https://github.com/IBM/platform-services-python-sdk/pull/12

test(IAM Access Groups): Fixed a bug in a temporary test fix

---

test/integration/test_global_catalog_v1.py

Use timestamp for child entry name and delete duplicate test.

test(GlobalCatalog): clean up some test cases

---

ibm_platform_services/global_catalog_v1.py
test/integration/test_global_catalog_v1.py
test/unit/test_global_catalog_v1.py

This PR contains a regen of the Global Catalog service after recent changes to the API definition.
**Fixes:** n/a

fix(Global Catalog): regen service with new API definition

---

ibm_platform_services/global_catalog_v1.py
test/unit/test_global_catalog_v1.py

This PR contains a re-generation of the Global Catalog service using the most recent version of the API definition.
**Fixes:**

fix(Global Catalog): re-generate service from latest API definition

---

.travis.yml

This PR disabled integration tests during tagged-release builds.

fix(build): disable integration tests during tagged-release builds

---

requirements.txt
test/integration/test_enterprise_management_v1.py

This PR fixes the EnterpriseManagement integration test.

test: fix date format used with account helper operation

---

test/integration/test_iam_policy_management_v1.py

Add integration tests for policy management module.
**Fixes:** <! -- link to issue -->

added policy management integration tests

---

Makefile

This PR adds a makefile to the project to make it easier to set up the project in a local sandbox for development work.

chore: add Makefile to improve dev experience

---

.travis.yml

Disables the integration tests for Case Mgmt, Enterprise Mgmt, and Resource Mgr services until they can be properly fixed.

build: disable failing int tests until they are fixed

---

.travis.yml

Re-enables the case-mgmt integraton tests

test: re-enable case-mgmt integration test

---

MANIFEST.in

This PR adds a MANIFEST.in file to ensure that all required files are included in the project's source distribution.

fix: include additional required files in src dist

---

ibm_platform_services/case_management_v1.py
ibm_platform_services/enterprise_management_v1.py
ibm_platform_services/global_catalog_v1.py
ibm_platform_services/global_search_v2.py
ibm_platform_services/global_tagging_v1.py
ibm_platform_services/iam_access_groups_v2.py
ibm_platform_services/iam_policy_management_v1.py
ibm_platform_services/resource_manager_v2.py
test/unit/test_case_management_v1.py
test/unit/test_enterprise_management_v1.py
test/unit/test_global_catalog_v1.py
test/unit/test_global_search_v2.py
test/unit/test_global_tagging_v1.py
test/unit/test_iam_access_groups_v2.py
test/unit/test_resource_manager_v2.py

This PR includes updated SDK service and unit test code for several services... the result of re-generating using the latest API definitions and SDK generator.

fix: regenerate services using latest SDK generator and API definitions

---

.travis.yml
tox.ini

Disable integration tests in travis builds because they are too unreliable

test: disable integration tests in travis builds

---

Makefile
requirements.txt
test/integration/test_case_management_v1.py
test/integration/test_catalog_management_v1.py

This PR contains some minor fixes to the case-mgmt and catalog-mgmt integration tests.

test: fix case-mgmt and catalog-mgmt integration tests

---

Makefile
pylint.sh
requirements-dev.txt
requirements.txt
test/unit/__init__.py

This PR makes adjustments to the various commands used to test/lint-check the project to use the
`python -m <command>` style.

chore: use python -m commands

---

README.md
examples/test_configuration_governance_v1_examples.py
ibm_platform_services/__init__.py
ibm_platform_services/configuration_governance_v1.py
test/integration/test_configuration_governance_v1.py
test/unit/test_configuration_governance_v1.py

This PR adds the Configuration Governance service to the project.

feat(Configuration Governance): add service to project

---

examples/__init__.py
pylint.sh
test/integration/test_case_management_v1.py
test/integration/test_catalog_management_v1.py
test/integration/test_enterprise_management_v1.py
test/integration/test_global_catalog_v1.py
test/integration/test_global_search_v2.py
test/integration/test_global_tagging_v1.py
test/integration/test_iam_access_groups_v2.py
test/integration/test_iam_policy_management_v1.py
test/integration/test_open_service_broker_v1.py
test/integration/test_resource_controller_v2.py
test/integration/test_resource_manager_v2.py
test/integration/test_user_management_v1.py
test/unit/test_catalog_management_v1.py
tox.ini

This PR adds lint-checking to the test/unit, test/integration and examples directories, plus includes fixes for the current set of lint warnings.

chore: fix lint warnings

---

requirements-dev.txt
tox.ini

This PR reverts some recent changes to tox.ini.

chore: fix tox error re: pytest-rerunfailures

---

tox.ini

chore: add back lint directories

---

examples/test_iam_identity_v1_examples.py
ibm_platform_services/iam_identity_v1.py
requirements.txt
test/integration/test_iam_identity_v1.py
test/integration/test_open_service_broker_v1.py
test/integration/test_resource_manager_v2.py
test/unit/test_iam_identity_v1.py

This PR contains a regen of the IAM Identity service after recent API definition updates.

fix(IAM Identity): regen service after API definition updates

---

README.md
codecov.yml
examples/test_usage_reports_v4_examples.py
ibm_platform_services/__init__.py
ibm_platform_services/usage_reports_v4.py
test/integration/test_usage_reports_v4.py
test/unit/test_usage_reports_v4.py

This PR adds the Usage Reports v4 service to the project, including integration tests and examples.

feat(Usage Reports): add service to project

---

README.md
examples/test_enterprise_usage_reports_v1_examples.py
ibm_platform_services/__init__.py
ibm_platform_services/enterprise_usage_reports_v1.py
test/integration/test_enterprise_usage_reports_v1.py
test/unit/test_enterprise_usage_reports_v1.py

This PR adds the Enterprise Usage Reports service to the project, including integration tests and examples.

feat(Enterprise Usage Reports): add service to project

---

examples/test_configuration_governance_v1_examples.py
ibm_platform_services/configuration_governance_v1.py
test/integration/test_configuration_governance_v1.py
test/unit/test_configuration_governance_v1.py

Updates the Config Governance service after recent API changes

fix(Configuration Governance): update service after API changes

---

ibm_platform_services/iam_identity_v1.py
requirements.txt
test/integration/test_iam_identity_v1.py
test/unit/test_iam_identity_v1.py

This PR contains a re-gen of IAM Identity after recent API updates.

Datetime updates

---

ibm_platform_services/user_management_v1.py
test/integration/test_user_management_v1.py
test/unit/test_user_management_v1.py

This PR contains a re-gen of the User Management  service plus updates to the integration tests after recent API changes.

fix(User Management): re-gen service and update tests after API changes

---

README.md
examples/test_usage_metering_v4_examples.py
ibm_platform_services/__init__.py
ibm_platform_services/usage_metering_v4.py
test/integration/test_usage_metering_v4.py
test/unit/test_usage_metering_v4.py

This PR adds the Usage Metering service to the project.

feat(Usage Metering): add service to project

---

examples/test_global_search_v2_examples.py
ibm_platform_services/case_management_v1.py
ibm_platform_services/configuration_governance_v1.py
ibm_platform_services/enterprise_billing_units_v1.py
ibm_platform_services/enterprise_management_v1.py
ibm_platform_services/enterprise_usage_reports_v1.py
ibm_platform_services/global_catalog_v1.py
ibm_platform_services/global_search_v2.py
ibm_platform_services/global_tagging_v1.py
test/integration/test_global_search_v2.py
test/unit/test_case_management_v1.py
test/unit/test_global_search_v2.py

This PR contains a re-gen of several services and adds examples for the Global Search service.

re-gen services and add examples

---

requirements-dev.txt
requirements.txt

This PR updates a few dependencies to use newer versions.

fix(build): update dependencies to avoid vulnerabilities

---

requirements.txt

Upgrades python core to v3.3.6

fix(deps): use python core v3.3.6

---

ibm_platform_services/iam_access_groups_v2.py
test/unit/test_iam_access_groups_v2.py

fix(IAM Access Groups): minor code re-gen after recent API changes

---

examples/test_configuration_governance_v1_examples.py
ibm_platform_services/configuration_governance_v1.py
test/unit/test_configuration_governance_v1.py

**Fixes:** <! -- link to issue -->

fix(Configuration Governance): re-gen service after recent API changes

---

examples/test_global_tagging_v1_examples.py
ibm_platform_services/global_tagging_v1.py
test/integration/test_global_tagging_v1.py
test/unit/test_global_tagging_v1.py

This PR updates the Global Tagging service after recent changes to the API definition.

fix(Global Tagging): update service after recent API changes

---

test/integration/test_case_management_v1.py

This PR makes some minor changes to the Case Management integration test.

test(Case Management): minor fixes to case-mgmt integration test

---

test/integration/test_case_management_v1.py

This PR is a simple change to the Case Management integration test to use pagination with the get_cases() operation.

test(Case Management): use pagination with get_cases operation

---

examples/test_user_management_v1_examples.py
test/integration/test_user_management_v1.py

This PR adds examples to the User Management service.

fix(User Management): add examples

---

examples/test_resource_controller_v2_examples.py
ibm_platform_services/resource_controller_v2.py
test/integration/test_resource_controller_v2.py
test/unit/test_resource_controller_v2.py

This PR contains a re-gen of the Resource Controller service and unit test code, along with updates to the integration tests and examples.

fix(Resource Controller): update service after recent API changes

---

.secrets.baseline
examples/test_iam_identity_v1_examples.py
ibm_platform_services/iam_identity_v1.py
test/integration/test_iam_identity_v1.py
test/unit/test_iam_identity_v1.py

This PR contains an update to the IAM Identity service - including integration tests and examples - after some recent changes to the API definition.

fix(IAM Identity): update service after recent API changes

---

test/integration/test_enterprise_management_v1.py
test/integration/test_global_catalog_v1.py
test/integration/test_open_service_broker_v1.py

Remove leftover dotenv imports and use the internal `read_external_sources` where needed.

fix: remove dotenv

---

ibm_platform_services/global_search_v2.py

This PR updates the Global Search service after recent API changes.

fix(Global Search): update service after recent API changes

---

.secrets.baseline
README.md
examples/test_posture_management_v1_examples.py
ibm_platform_services/posture_management_v1.py
test/integration/test_posture_management_v1.py
test/unit/test_posture_management_v1.py

This PR adds the Posture Management service to the project.

feat(Posture Management): add service to project

---

examples/test_resource_controller_v2_examples.py

This PR modifies the Resource Controller working examples so that the labels displayed in the output will not be included in the API reference.

chore: hide labels from API reference

---

ibm_platform_services/resource_controller_v2.py
test/unit/test_resource_controller_v2.py

fix(resource controller): update sdk after recent api changes

---

requirements.txt

fix(deps): update dependencies

---

examples/test_iam_policy_management_v1_examples.py
ibm_platform_services/iam_policy_management_v1.py
test/integration/test_iam_policy_management_v1.py
test/unit/test_iam_policy_management_v1.py

Updating SDK to include new changes from API for PATCH for v1/policies and additional new params. 

fix(IAM Policy Management): add restore policy functionality

---

CODE_OF_CONDUCT.md
setup.py

Updates email addresses to use devxsdk@us.ibm.com

build: update owner email address

---

examples/test_enterprise_management_v1_examples.py
ibm_platform_services/enterprise_management_v1.py
test/integration/test_enterprise_management_v1.py
test/unit/test_enterprise_management_v1.py

This PR updates the Enterprise Management service after recent API changes. Also adds working examples.

fix(Enterprise Management): update service after recent API changes and add examples

---

ibm_platform_services/enterprise_management_v1.py
test/unit/test_enterprise_management_v1.py

Re-gen of service after API changes.

fix(Enterprise Management): update service after API changes

---

examples/test_case_management_v1_examples.py
examples/test_configuration_governance_v1_examples.py
examples/test_enterprise_billing_units_v1_examples.py
examples/test_enterprise_management_v1_examples.py
examples/test_enterprise_usage_reports_v1_examples.py
examples/test_global_catalog_v1_examples.py
examples/test_global_search_v2_examples.py
examples/test_global_tagging_v1_examples.py
examples/test_iam_access_groups_v2_examples.py
examples/test_iam_identity_v1_examples.py
examples/test_iam_policy_management_v1_examples.py
examples/test_open_service_broker_v1_examples.py
examples/test_posture_management_v1_examples.py
examples/test_resource_manager_v2_examples.py
examples/test_usage_metering_v4_examples.py
examples/test_usage_reports_v4_examples.py
examples/test_user_management_v1_examples.py
ibm_platform_services/__init__.py

fix: example labels

---

README.md

This PR simply adds a new "module name" column to the service table in the README

docs: add module names to service table

---

ibm_platform_services/resource_controller_v2.py
test/integration/test_resource_controller_v2.py
test/unit/test_resource_controller_v2.py

PR for resource controller service update and integration test changes 

fix(Resource Controller): update service after api changes

---

ibm_platform_services/iam_identity_v1.py

fix(IAM Identity): re-gen service after recent API changes

---

requirements.txt
test/unit/test_global_search_v2.py
test/unit/test_global_tagging_v1.py

This PR upgrades our core dependency to version 3.10.0, and renames a few unit test classes (for search and tagging) to account for a bug in the v3.33.0 SDK generator.

build: upgrade core dependency to 3.10.0

---

ibm_platform_services/iam_access_groups_v2.py
test/unit/test_iam_access_groups_v2.py

fix(IAM Access Groups): update service after recent api changes

---

.secrets.baseline
ibm_platform_services/catalog_management_v1.py
test/integration/test_catalog_management_v1.py
test/integration/test_catalog_management_v1_old.py
test/unit/test_catalog_management_v1.py

This PR contains the update for Catalog Management SDK after the Api recent changes.
**Important to note**:
- the tests where I had issues (user is not granted, no suitable data or lack of my domain knowledge) has comments about the details, even though it is ugly but hopefully informative to the team, so they can find solutions easily
- Integration test data and parameters are conherent across SDKs except the cases where  the language name was used
- as the amount of catalogs grows the `listCatalogs` method will fail more and more due to that the database query has a limit on the result set. Many times the newly created catalog is not in the result. It is discussed with Jon.
**About coverage**:
- Except 4 operations all operattion has at least one test exercising either the happy path or …

fix(catalog-management): update Catalog Management SDK after recent changes

---

README.md
examples/test_ibm_cloud_shell_v1_examples.py
ibm_platform_services/__init__.py
ibm_platform_services/ibm_cloud_shell_v1.py
test/integration/test_ibm_cloud_shell_v1.py
test/unit/test_ibm_cloud_shell_v1.py

feat(Cloudshell): add service, tests and examples to project

---

ibm_platform_services/usage_reports_v4.py
test/unit/test_usage_reports_v4.py

add optional name parameters to data type
Names will now show up when the optional parameter _names is passed

fix(Usage Reports): add optional name parameters to struct

---

README.md

This PR changes the Reference urls in the README file and as a result when the user clicks on it they will be taken away to IBM's Reference site where the examples will be displayed on the right language, in this case python.

docs: add lang code to README.md's reference urls

---

requirements.txt

This PR bumps the python core version to 3.11.0 to pull in the ContainerAuthenticator functionality.

fix: bump python core version to 3.11.0

---

requirements.txt

This PR bumps up our python core version to 3.11.3 to pull in the authenticator fix.

fix(build): bump python core version to 3.11.3

---

examples/test_iam_identity_v1_examples.py
ibm_platform_services/iam_identity_v1.py
test/integration/test_iam_identity_v1.py
test/unit/test_iam_identity_v1.py

feat(iam-identity): adding trusted profiles

---

examples/test_iam_identity_v1_examples.py

docs: fix documentation

---

examples/test_iam_identity_v1_examples.py
ibm_platform_services/iam_identity_v1.py
test/integration/test_iam_identity_v1.py
test/unit/test_iam_identity_v1.py

feat(iam-identity): fixing examples

---

.travis.yml

Bumps node to version 14 to accommodate the new semantic-release v18.

chore(build): use node 14 for new semantic-release version

---

examples/test_context_based_restrictions_v1_examples.py
ibm_platform_services/context_based_restrictions_v1.py
test/integration/test_context_based_restrictions_v1.py
test/unit/test_context_based_restrictions_v1.py

Added context-based-restrictions python sdk with integration tests, and examples

feat(Context-Based Restrictions): add service and tests to project

---

.secrets.baseline

Attempt to fix the false positive being reported in slack.

chore: fix detect-secrets false positive

---

requirements.txt

This PR bumps up our python core dependency to 3.13.0

fix: bump python core to 3.13.0

---

Makefile
requirements-dev.txt

This PR removes the codecov tool from the project due to security vulnerabilities

build: remove codecov from project

---

.secrets.baseline
examples/test_iam_access_groups_v2_examples.py
ibm_platform_services/iam_access_groups_v2.py
test/unit/test_iam_access_groups_v2.py

fix(IAM Access Groups): update service after service url adjustment

---

ibm_platform_services/catalog_management_v1.py
test/integration/test_catalog_management_v1.py
test/unit/test_catalog_management_v1.py

Re-generated the Catalog Management SDK code to contain the new PATCH operation for offerings.
Add support for PATCH offerings.

fix(Catalog Management): update service to add patch operation

---

ibm_platform_services/iam_access_groups_v2.py
test/unit/test_iam_access_groups_v2.py

Add trusted profile as new member to Access group

fix(IAM Access Groups): Add new member trusted profile as ag member

---

.travis.yml
README.md
setup.py

This PR drops the support for Python 3.6 and adds support for Python 3.10.

build: update Python versions

---

requirements.txt

This PR bumps the Python core to 3.15.1

fix: bump core to v3.15.1

---

examples/test_iam_access_groups_v2_examples.py
ibm_platform_services/iam_access_groups_v2.py
test/integration/test_iam_access_groups_v2.py
test/unit/test_iam_access_groups_v2.py

this Pr includes the changes for dynamic membership in access groups

feat(IAM Access Groups): add support for dynamic membership

---

examples/test_iam_identity_v1_examples.py

test(IAM Identity): update examples with right tags

---

ibm_platform_services/iam_identity_v1.py
test/integration/test_iam_identity_v1.py
test/unit/test_iam_identity_v1.py

The report schema is slightly improvised, incorporating the changes into SDKs

fix(IAM Identity): update report schema and fix ITs

---

README.md
examples/test_context_based_restrictions_v1_examples.py
ibm_platform_services/context_based_restrictions_v1.py
test/integration/test_context_based_restrictions_v1.py
test/unit/test_context_based_restrictions_v1.py

Context based Restrictions API update to include enforcement mode support
add `enforcement mode` to rule

feat(Context based Restrictions): enforcement mode support

---

requirements.txt

This PR bumps up our python core version to the most recent.

build: bump python core to most recent

---

examples/test_context_based_restrictions_v1_examples.py

Signed-off-by: Stephen SooHoo <soohoos@us.ibm.com>
Better SDK example alignment with curl examples.

refactor(Context-based Restrictions): update create zone examples

---

examples/test_iam_identity_v1_examples.py
examples/test_ibm_cloud_shell_v1_examples.py
examples/test_open_service_broker_v1_examples.py
ibm_platform_services/case_management_v1.py
ibm_platform_services/catalog_management_v1.py
ibm_platform_services/common.py
ibm_platform_services/configuration_governance_v1.py
ibm_platform_services/context_based_restrictions_v1.py
ibm_platform_services/enterprise_billing_units_v1.py
ibm_platform_services/enterprise_management_v1.py
ibm_platform_services/enterprise_usage_reports_v1.py
ibm_platform_services/global_catalog_v1.py
ibm_platform_services/global_search_v2.py
ibm_platform_services/global_tagging_v1.py
ibm_platform_services/iam_access_groups_v2.py
ibm_platform_services/iam_identity_v1.py
ibm_platform_services/iam_policy_management_v1.py
ibm_platform_services/ibm_cloud_shell_v1.py
ibm_platform_services/open_service_broker_v1.py
ibm_platform_services/posture_management_v1.py
ibm_platform_services/resource_controller_v2.py
ibm_platform_services/resource_manager_v2.py
ibm_platform_services/usage_metering_v4.py
ibm_platform_services/usage_reports_v4.py
ibm_platform_services/user_management_v1.py
test/integration/test_catalog_management_v1.py
test/integration/test_context_based_restrictions_v1.py
test/integration/test_iam_identity_v1.py
test/integration/test_resource_controller_v2.py

This PR removes the trailing whitespaces from the Python
files to fix the builds, because a recently released Pylint started
to complain.
Signed-off-by: Norbert Biczo <pyrooka@users.noreply.github.com>

chore: remove trailing whitespaces from Python files

---

examples/test_context_based_restrictions_v1_examples.py
ibm_platform_services/context_based_restrictions_v1.py
test/integration/test_context_based_restrictions_v1.py
test/unit/test_context_based_restrictions_v1.py

This PR adds CBR support for the new service_group_id parameter in rules.
No current behavior should be modified. Adds the further control to be able to apply rules to service groups

add test: list rule with service group

---

examples/test_case_management_v1_examples.py
ibm_platform_services/case_management_v1.py
test/integration/test_case_management_v1.py
test/unit/test_case_management_v1.py

This commit contains a re-gen of the service to
leverage the new Pagers emitted by the SDK
generator.

fix(Case Management): regen service to add Pager

---

README.md

Small change to README to provide example of python import for a service

docs: add python import example to README

---

.secrets.baseline
examples/test_enterprise_usage_reports_v1_examples.py
ibm_platform_services/enterprise_usage_reports_v1.py
test/integration/test_enterprise_usage_reports_v1.py
test/unit/test_enterprise_usage_reports_v1.py

This commit contains a re-gen of the service to
leverage the new Pagers emitted by the SDK generator.

fix(Enterprise Usage Reports): regen service to get Pager

---

.secrets.baseline
examples/test_iam_access_groups_v2_examples.py
ibm_platform_services/iam_access_groups_v2.py
test/integration/test_iam_access_groups_v2.py
test/unit/test_iam_access_groups_v2.py

This commit contains a re-gen of the service to
leverage the new Pagers emitted by the SDK generator.

fix(IAM Access Groups): regen service to get Pagers

---

.secrets.baseline
examples/test_resource_controller_v2_examples.py
ibm_platform_services/resource_controller_v2.py
test/integration/test_resource_controller_v2.py
test/unit/test_resource_controller_v2.py

This commit contains a re-gen of the Resource Controller service to leverage the new Pagers emitted by the SDK generator.

fix(Resource Controller): re-gen service to get new Pagers

---

.secrets.baseline
examples/test_enterprise_management_v1_examples.py
ibm_platform_services/enterprise_management_v1.py
test/integration/test_enterprise_management_v1.py
test/unit/test_enterprise_management_v1.py

This commit contains a re-gen of the Enterprise Management service to leverage the new Pagers emitted by the SDK generator.

fix(Enterprise Management): re-gen service to get new Pagers

---

examples/test_iam_identity_v1_examples.py
ibm_platform_services/iam_identity_v1.py
requirements-dev.txt
test/integration/test_iam_identity_v1.py
test/unit/test_iam_identity_v1.py

Python SDK doc for IAM identity. PR includes changes related
Create mfa report
Get mfa report
Get mfa user status
Change token expiration max and default value to 259200

fix(IAM Identity): re-gen with latest API definition

---

ibm_platform_services/global_search_v2.py
test/unit/test_global_search_v2.py

removed an internal search parameter: is_hidden

fix(Global Search): remove is_hidden param from search operation

---

requirements.txt

Bumps the python core version to 4.16.5.

build: bump python core version to 4.16.5

---

examples/test_iam_access_groups_v2_examples.py
ibm_platform_services/iam_access_groups_v2.py
test/unit/test_iam_access_groups_v2.py

feat (IAM Access Groups): Enable search during list groups

---

ibm_platform_services/enterprise_management_v1.py
test/unit/test_enterprise_management_v1.py

re-gen service after update trait object

feat(Enterprise Management): re-gen service after update trait object

---

.travis.yml

This PR modifies our .travis.yml file to ensure that pip is upgraded to its latest version before building the project.  This is being done to avoid pip-related errors during the build.

build: use latest pip during build

---

examples/test_iam_access_groups_v2_examples.py
ibm_platform_services/iam_access_groups_v2.py
test/integration/test_iam_access_groups_v2.py
test/unit/test_iam_access_groups_v2.py

SDK adopters will be able to call access group template and assignment APIs.
API Definition
[Stage](https://test.cloud.ibm.com/docs/access-groups)
[Production](https://cloud.ibm.com/docs/access-groups)
Example Tests

feat (IAM Access Groups): Add support for access group templates

---

Makefile

build: remove blank from Makefile

---

ibm_platform_services/global_search_v2.py
ibm_platform_services/global_tagging_v1.py
test/unit/test_global_search_v2.py
test/unit/test_global_tagging_v1.py

fix(Global Search/Tagging): regenerated services with latest API definition
defined tracing headers for GhoST search and tagging apis.
deprecated transaction-id header parameter

fix(Global Search/Tagging): regenerated services with latest API definition

---

.secrets.baseline

build: fix detect-secrets issues

---

ibm_platform_services/usage_reports_v4.py
test/unit/test_usage_reports_v4.py

Add new query parameters to support pagination of API: /v1/billing-reports-snapshots

feat(Usage Reports): Update query param for getting reports snapshotlist

---

.secrets.baseline

build: fix false positive detect-secrets alert

---

ibm_platform_services/iam_policy_management_v1.py
test/unit/test_iam_policy_management_v1.py

Updated based on API definition fix to allow for `conditions` under `rule.conditions`.
Tests:
Examples:
```sh
pytest examples/test_iam_policy_management_v1_examples.py 
======================================================================================== test session starts =========================================================================================
...
collected 28 items                                                                                                                                                                                   
examples/test_iam_policy_management_v1_examples.py ............................                                                                                                                [100%] …
```

fix(IAM Policy Management): Added nest conditions to rule.conditions

---

examples/test_context_based_restrictions_v1_examples.py
ibm_platform_services/context_based_restrictions_v1.py
test/unit/test_context_based_restrictions_v1.py

- add new field to /v1/operations response
- fix zone example values
- support /v1/operations 'enforcement_modes' response field
- add IPv6 examples for doc/SDK consistency

feat(Context-Based Restrictions): add enforcement_modes to operations response

---

examples/test_iam_policy_management_v1_examples.py
ibm_platform_services/iam_policy_management_v1.py
test/integration/test_iam_policy_management_v1.py
test/unit/test_iam_policy_management_v1.py

Updated based on minor api definition update.
```sh
pytest test/integration/test_iam_policy_management_v1.py
=================================================================================== test session starts ===================================================================================
platform darwin -- Python 3.10.12, pytest-7.2.0, pluggy-1.0.0
rootdir: /Users/shaunsmacibm/Desktop/cloud-platform/iam/sdk/platform-services-python-sdk
plugins: cov-2.12.1
collected 27 items                                                                                                                                                                        
test/integration/test_iam_policy_management_v1.py …
```

fix(IAM Policy Management): add nested conditions to rule.conditions

---

.secrets.baseline
examples/test_iam_identity_v1_examples.py
ibm_platform_services/iam_identity_v1.py
test/integration/test_iam_identity_v1.py
test/unit/test_iam_identity_v1.py

add new field to /v1/mfa/accounts/{account_id}/report/{reference} response

feat(IAM Identity): add comply_state variable to mfa report

---

ibm_platform_services/global_search_v2.py
ibm_platform_services/global_tagging_v1.py
test/unit/test_global_search_v2.py
test/unit/test_global_tagging_v1.py

fix(Global Tagging): regenerate service using latest API definition

---

examples/test_usage_reports_v4_examples.py
ibm_platform_services/usage_reports_v4.py
test/integration/test_usage_reports_v4.py
test/unit/test_usage_reports_v4.py

Adding new API to validate s2s authentication in billing snapshot configuration service in usage reports.
TRI: https://github.ibm.com/BSS/architecture/blob/master/design-docs/services/billing/apptio-integration.md
Issue: https://github.ibm.com/BSS/metering-deliverables/issues/2102

feat(Usage Reports): add billing snapshot config validate service to usage reports

---

requirements.txt

bumps python core version to the latest

fix: bump python core to v3.18.1

---

requirements.txt

build: bump python core to 3.18.2

---

ibm_platform_services/iam_policy_management_v1.py
test/integration/test_iam_policy_management_v1.py
test/unit/test_iam_policy_management_v1.py

issue: https://github.ibm.com/IAM/AM-issues/issues/1949

feat(IAM Policy Management): re-gen service after fix the template state parameter

---

requirements.txt

This PR bumps the python core to the latest (3.19.1)

build: bump python core to 3.19.1

---

.secrets.baseline

Updates .secrets.baseline to add new false positive.

build: add new false positive to .secrets.baseline

---

ibm_platform_services/global_search_v2.py
ibm_platform_services/global_tagging_v1.py
test/unit/test_global_search_v2.py
test/unit/test_global_tagging_v1.py

New documentation about `replace` on get-tags swagger

fix(Global Search/Tagging): re-gen services with latest API definition

---

examples/test_iam_identity_v1_examples.py
ibm_platform_services/iam_identity_v1.py
test/integration/test_iam_identity_v1.py
test/unit/test_iam_identity_v1.py

Add support for new endpoint
Update examples to match the API
API defintion:
[Staging](https://test.cloud.ibm.com/apidocs/iam-identity-token-api?code=java#get-profile-identities)
Test information:
test\integration\test_iam_identity_v1.py .........................................................................................                    [100%]
============================================================== 89 passed in 681.09s (0:11:21) ==============================================================
examples\test_iam_identity_v1_examples.py ......................................................................                                      [100%] …

feat(IAM Identity): add disable_api_key and enable_api_key operations

---

ibm_platform_services/enterprise_management_v1.py
test/integration/test_enterprise_management_v1.py
test/unit/test_enterprise_management_v1.py

add options property to create_account payload

fix(Enterprise Management): add options property to create_account payload

---

ibm_platform_services/global_search_v2.py
ibm_platform_services/global_tagging_v1.py
test/integration/test_global_search_v2.py
test/unit/test_global_search_v2.py
test/unit/test_global_tagging_v1.py

Removed all references to transdaction-id

fix(Global Search & Tagging): re-gen services with latest API definition

---

ibm_platform_services/enterprise_management_v1.py
test/unit/test_enterprise_management_v1.py

Re-Generated sdk after recent create_account response changes in create enterprise child account api

fix(Enterprise Management): re-gen service after recent create_account response changes

---

examples/test_iam_policy_management_v1_examples.py
ibm_platform_services/iam_policy_management_v1.py
test/integration/test_iam_policy_management_v1.py
test/unit/test_iam_policy_management_v1.py

fix(IAM Policy Management): remove `options` property from PolicyAssignment

---

requirements.txt

build: bump Python core to 3.20.3

---

setup.py

This PR contains a really small change to setup.py in order to force a new release to be published.  This is being done primarily to test a small config change in our Travis build settings.

fix(build): add python 3.12 tag to setup.py

---

.travis.yml

This PR modifies our travis build config to add python 3.12

build: build on python 3.12

---

examples/test_iam_identity_v1_examples.py
ibm_platform_services/iam_identity_v1.py
test/integration/test_iam_identity_v1.py
test/unit/test_iam_identity_v1.py

new endpoint to get Effective account settings,
also has action control added to existing template calls.

feat(IAM Identity): adding effective account settings

---

ibm_platform_services/resource_controller_v2.py

feat(Resource Controller): deprecate alias, bindings APIs, and related schema items

---

.github/workflows/build.yaml
.github/workflows/publish.yaml
.secrets.baseline
Makefile

This PR enables GitHub Actions for the project, as an alternative to Travis-CI.

fix: enable github workflows

---

ibm_platform_services/iam_access_groups_v2.py
test/integration/test_iam_access_groups_v2.py
test/unit/test_iam_access_groups_v2.py

feat(IAM Access Groups): Add CRN filter

---

ibm_platform_services/usage_reports_v4.py
test/unit/test_usage_reports_v4.py

feat(Usage Reports): added subscription_id, created_at, deleted_at to InstanceUsage API response

---

ibm_platform_services/global_search_v2.py
test/unit/test_global_search_v2.py

fix(Global Search): regenerated services with latest API definition
