IBM/platform-services-python-sdk

- .travis.yml
**Fixes:** run integration tests only in python 3.5 to avoid rate limiting
> chore: Make integration tests run only in python 3.5

- ibm_platform_services/resource_manager_v2.py
- test/unit/test_resource_manager_v2.py
This PR contains a re-generation of the Resource Manager service after
recent changes to the API definition.
**Fixes:** n/a
> fix(Resource Manager): re-gen service after API definition updates

- MANIFEST.in
- README.md
This PR makes minor changes to the README.md so that when it is displayed on the pypi.org project page, the links to LICENSE and CONTRIBUTING.md will correctly point back to the github repo.
> fix: use absolute URLs in README.md

- README.md
- ibm_platform_services/__init__.py
- ibm_platform_services/user_management_v1.py
- test/integration/test_integration_user_management_v1.py
- test/unit/test_user_management_v1.py
This PR adds the User Management service to the project.
> feat(User Management): add service to project

- examples/test_global_tagging_v1_examples.py
- ibm_platform_services/global_tagging_v1.py
- test/integration/test_global_tagging_v1.py
- test/unit/test_global_tagging_v1.py
This PR contains:
* a re-gen of the service and unit test code for the Global Tagging service
* a renovated integration test starting with a new generated test
* a new request examples file
> fix(Global Tagging): re-gen service with latest API definition

- README.md
- examples/test_iam_identity_v1_examples.py
- ibm_platform_services/__init__.py
- ibm_platform_services/iam_identity_v1.py
- test/integration/test_iam_identity_v1.py
- test/unit/test_iam_identity_v1.py
This PR adds the IAM Identity service to the project.
> feat(IAM Identity): add service to the project

- .travis.yml
- Makefile
- README.md
- requirements-dev.txt
- requirements.txt
- setup.py
- test/integration/test_catalog_management_v1.py
- tox.ini
This commit updates the minimum supported python version
from 3.5 to 3.6 (python 3.5 has already passed its
"end of service" date), and adds support for building/testing
on python 3.9.
> fix(deps): move to python 3.6 as minimum supported level

- examples/test_case_management_v1_examples.py
- ibm_platform_services/case_management_v1.py
- test/unit/test_case_management_v1.py
This PR adds examples to the Case Management service.
> fix(Case Management): re-gen service and add examples

- .github/pull_request_template.md
- Makefile
- examples/test_case_management_v1_examples.py
- examples/test_configuration_governance_v1_examples.py
- examples/test_enterprise_billing_units_v1_examples.py
- examples/test_enterprise_usage_reports_v1_examples.py
- examples/test_global_catalog_v1_examples.py
- examples/test_global_search_v2_examples.py
- examples/test_global_tagging_v1_examples.py
- examples/test_iam_access_groups_v2_examples.py
- examples/test_iam_identity_v1_examples.py
- examples/test_open_service_broker_v1_examples.py
- examples/test_resource_controller_v2_examples.py
- examples/test_usage_metering_v4_examples.py
- examples/test_usage_reports_v4_examples.py
Fixes up comments in examples.
> chore: fix-up config comments in examples

- examples/test_resource_manager_v2_examples.py
- ibm_platform_services/resource_manager_v2.py
- test/integration/test_resource_manager_v2.py
- test/unit/test_resource_manager_v2.py
This PR updates the Resource Manager service and also add examples.
> fix(Resource Manager): update service after recent API changes and generate examples

- examples/test_case_management_v1_examples.py
- examples/test_configuration_governance_v1_examples.py
- examples/test_enterprise_billing_units_v1_examples.py
- examples/test_enterprise_usage_reports_v1_examples.py
- examples/test_global_catalog_v1_examples.py
- examples/test_global_search_v2_examples.py
- examples/test_global_tagging_v1_examples.py
- examples/test_iam_access_groups_v2_examples.py
- examples/test_iam_identity_v1_examples.py
- examples/test_iam_policy_management_v1_examples.py
- examples/test_open_service_broker_v1_examples.py
- examples/test_resource_controller_v2_examples.py
- examples/test_resource_manager_v2_examples.py
- examples/test_usage_metering_v4_examples.py
- examples/test_usage_reports_v4_examples.py
- examples/test_user_management_v1_examples.py
This PR adds labels to example output, so it is easier to identify which output section belongs to which method.
> fix: add labels to examples

- .secrets.baseline
- ibm_platform_services/iam_access_groups_v2.py
- test/unit/test_iam_access_groups_v2.py
> fix(iam access groups): update sdk after recent api changes

- ibm_platform_services/iam_identity_v1.py
- test/integration/test_iam_identity_v1.py
- test/unit/test_iam_identity_v1.py
This PR contains the re-generated IAM Identity service and the updated integration tests.
> fix(IAM Identity): update service after recent API changes

- ibm_platform_services/context_based_restrictions_v1.py
- test/integration/test_context_based_restrictions_v1.py
- test/unit/test_context_based_restrictions_v1.py
Added support for the X-Correlation-Id header
*Added support for passing the standard X-Correlation-Id header in each request
*Updated some swagger properties summaries and descriptions
This enhancement adds support for passing the standard X-Correlation-Id header in each request. This is an optional header and it does not break backward compatibility.
> Added support for X-Correlation-id header

- .travis.yml
- requirements-dev.txt
This PR updates pytest to the next major version (7.x.x) and pins the `setuptools` package version in the Travis deploy step to fix publishing to PyPi.
~~NOTE: Python 3.6 is no longer supported officially, but it seems to work.~~
> build: update pytest to v7

- examples/test_iam_identity_v1_examples.py
- ibm_platform_services/iam_identity_v1.py
- test/integration/test_iam_identity_v1.py
- test/unit/test_iam_identity_v1.py
adding new endpoints: create report, get report
adding new optional query parameter include_activity for the existing get calls of apikey/serviceid/profile by id.
users will now be able to generate report for inactive identities.
create report: will return a reference
get report: this will return a detailed report of inactive identities
existing get apikey/serviceid/profile by id will now include additional optional parameter include_activity
if include_activity is passed as true the response will include a new section activity with last authn time and count.
> feat(IAM Identity): add support for inactivity reports

- requirements.txt
This PR bumps the python core to 3.15.2 so that a new version of PyJWT is pulled in (to avoid a vulnerability).
> fix: bump core to 3.15.2

- .travis.yml
This commit fixes the version of the `setuptools` package 
to fix build issues with Python 3.7 and 3.8.
Current: builds are failing for Python 3.7/8
New: hopefully every build will pass :)
> build: use fixed version of setuptools in Travis builds

- examples/test_resource_controller_v2_examples.py
- ibm_platform_services/resource_controller_v2.py
- test/integration/test_resource_controller_v2.py
- test/unit/test_resource_controller_v2.py
Signed-off-by: apoorva9s14 <apoorvalaiti16@gmail.com>
For the resource controller service update as per this PR - https://github.ibm.com/cloud-api-docs/resource-controller/pull/244, resource-controller-v2.yaml is the updated yaml, I have regenerated the SDK files with openapi-sdkgen.
We are looking to address:
Looping - https://github.ibm.com/cloud-api-docs/resource-controller/issues/226
Credentials redaction
- [ Yes] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ Yes] Docs have been added / updated (for bug fixes / features)
The examples and the SDK code snippet in the apidocs would be updated for …
> ResourceController service update

- .secrets.baseline
- examples/test_user_management_v1_examples.py
- ibm_platform_services/user_management_v1.py
- test/integration/test_user_management_v1.py
- test/unit/test_user_management_v1.py
This commit contains a re-gen of the User Management service to leverage the new Pagers emitted by the SDK generator.
> fix(User Management): re-gen service to get new Pagers

- examples/test_iam_policy_management_v1_examples.py
- ibm_platform_services/iam_policy_management_v1.py
- test/integration/test_iam_policy_management_v1.py
- test/unit/test_iam_policy_management_v1.py
Signed-off-by: Shaun Colley <shaun.colley@ibm.com>
Code to support new v2/policies API has been introduced. The new v2/policies API will have new JSON fields and existing v1/fields have been changed.
v1/policies API will continue to be supported.
PR's are currently open for staging and production docs. They are not currently merged:
Staging: https://github.ibm.com/cloud-api-docs/iam-access-management/pull/139
Production: https://github.ibm.com/cloud-api-docs/iam-access-management/pull/140
Current behavior will remain same (v1 will continue to be supported). New behavior is v2/policies support which allows for time based restriction policies using new rule field (an integration test has been added of this example).
See: …
> feat(IAM Policy Management): add support for v2/policies

- ibm_platform_services/usage_reports_v4.py
- test/unit/test_usage_reports_v4.py
Rename the `billing_month` property in the `Account_Summary` schema to `month`
The `Account_Summary` schema should now correctly have the `month` property instead of the `billing_month` property.
> fix: rename Account_Summary billing_month property

- examples/test_enterprise_management_v1_examples.py
- ibm_platform_services/enterprise_management_v1.py
- test/integration/test_enterprise_management_v1.py
- test/unit/test_enterprise_management_v1.py
> feat(enterprise management): re-gen service after recent API changes

- ibm_platform_services/enterprise_management_v1.py
- test/unit/test_enterprise_management_v1.py
Regenerate sdk after trait object schema change in create account object
> feat(Enterprise Management): re-gen after trait schema change

- examples/test_user_management_v1_examples.py
- ibm_platform_services/user_management_v1.py
- test/integration/test_user_management_v1.py
- test/unit/test_user_management_v1.py
Update Include_settings and substring search functionality (User Management) 
the current issue for updating SDK https://github.ibm.com/IAM/uum/issues/5882 
the previous issue for the user management code change https://github.ibm.com/IAM/uum/issues/4948
> feat (User Management): add query params search and include_settings to list_users operation

- ibm_platform_services/usage_reports_v4.py
- test/unit/test_usage_reports_v4.py
Updates Account Summary to reflect changes to the API
Updates Account Summary to reflect changes to the API
Examples:
```
===================================================================== test session starts ======================================================================
platform darwin -- Python 3.11.2, pytest-7.2.2, pluggy-1.0.0
rootdir: /platform-services-python-sdk
plugins: cov-2.12.1
collected 7 items                                                                                                                                              
test/integration/test_usage_reports_v4.py .......                                                                                                        [100%] …
```
> feat(Usage Reports): Update Account Summary

- examples/test_iam_identity_v1_examples.py
- ibm_platform_services/iam_identity_v1.py
- test/integration/test_iam_identity_v1.py
- test/unit/test_iam_identity_v1.py
Added feature support for Trusted Profile identities work, add, get, delete identities associated with the profile. 
SDK adopters will be able to call Trusted profile identities APIs.
API defintion:
[Staging](https://test.cloud.ibm.com/apidocs/iam-identity-token-api?code=java#get-profile-identities)
Test information:
```sh
========================================================== test session starts ===========================================================
platform win32 -- Python 3.10.9, pytest-7.3.1, pluggy-1.0.0
rootdir: C:\Users\SomanathChavan\SDK\platform-services-python-sdk
collected 41 items
examples\test_iam_identity_v1_examples.py ......................................... …
```
> feat(IAM Identity): add trusted profile identities api

- .travis.yml
- examples/test_iam_identity_v1_examples.py
- ibm_platform_services/iam_identity_v1.py
- test/integration/test_iam_identity_v1.py
- test/unit/test_iam_identity_v1.py
Added support for IAM enterprise feature. Enterprise admins can create templates for account settings and trusted profiles and assign them to accounts and account groups in the enterprise.
SDK adopters will be able to work with IAM enterprise feature.
API definition: [Staging](https://test.cloud.ibm.com/apidocs/iam-identity-token-api#list-profile-templates)
Test information:
```
==================================================== test session starts ====================================================
platform win32 -- Python 3.10.11, pytest-7.4.0, pluggy-1.2.0
rootdir: D:\BlueMix\repos\platform-services-python-sdk
collected 87 items
test\integration\test_iam_identity_v1.py …
```
> feat(IAM Identity): Add support for IAM enterprise

- .pylintrc
- CONTRIBUTING.md
- Makefile
- pylint.sh
- update_service.md
This PR modifies the project to allow developers to build and test the project on Windows.
> fix: enable builds on Windows

- examples/test_iam_access_groups_v2_examples.py
- ibm_platform_services/iam_access_groups_v2.py
- test/integration/test_iam_access_groups_v2.py
- test/unit/test_iam_access_groups_v2.py
Removed "update" field from create template & template version request body.
NA
> fix(IAM Access Groups): Remove update action control from assertions

- CHANGELOG.md
- examples/test_usage_reports_v4_examples.py
- ibm_platform_services/usage_reports_v4.py
- test/integration/test_usage_reports_v4.py
- test/unit/test_usage_reports_v4.py
Introducing new CRUD APIs to configure billing reports snapshot.
TRI: https://github.ibm.com/BSS/architecture/blob/master/design-docs/services/billing/apptio-integration.md
Issue: https://github.ibm.com/BSS/metering-deliverables/issues/1990
> feat(Usage Reports): add billing snapshot config service to usage reports

- examples/test_context_based_restrictions_v1_examples.py
- ibm_platform_services/context_based_restrictions_v1.py
- test/integration/test_context_based_restrictions_v1.py
- test/unit/test_context_based_restrictions_v1.py
Adds service group support to operations
service_name parameter can now be replaced with the service group parameter.
> feat(Context-Based Restrictions): add service group support to Operations

- examples/test_iam_policy_management_v1_examples.py
- ibm_platform_services/iam_policy_management_v1.py
- test/integration/test_iam_policy_management_v1.py
- test/unit/test_iam_policy_management_v1.py
Issue: https://github.ibm.com/IAM/AM-issues/issues/1803
```
pytest test/integration/test_iam_policy_management_v1.py 
==================================================================================================================== test session starts =====================================================================================================================
platform darwin -- Python 3.11.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /Users/rajesh/iam-project/platform-sdk/platform-services-python-sdk
plugins: cov-2.12.1
collected 27 items …
```
> feat(IAM Policy Management): re-gen service after fix the template metadata as part of policies

- ibm_platform_services/iam_policy_management_v1.py
- test/unit/test_iam_policy_management_v1.py
This is a minor regeneration based on update to enum for operators in v2/policies.
Issue: https://github.ibm.com/IAM/AM-issues/issues/2212
Tests:
```sh
pytest test/integration/test_iam_policy_management_v1.py 
================================================================== test session starts ===================================================================
platform darwin -- Python 3.9.17, pytest-7.4.4, pluggy-1.4.0
rootdir: /Users/shaunsmacibm/Desktop/cloud-platform/iam/sdk/platform-services-python-sdk
plugins: cov-4.1.0
collected 27 items …
```
> fix(IAM Policy Management): regenerate based on minor API update to operator

- ibm_platform_services/usage_reports_v4.py
- test/unit/test_usage_reports_v4.py
Regeneration of the usage reports service. Mainly intended to add `catalog_id` to `instance_usage` and `resource`.
Tests:
```
Name                                                     Stmts   Miss  Cover
----------------------------------------------------------------------------
ibm_platform_services/__init__.py                           24      0   100%
ibm_platform_services/case_management_v1.py               1189     96    92%
ibm_platform_services/catalog_management_v1.py            4502    186    96%
ibm_platform_services/common.py                             15      0   100%
ibm_platform_services/context_based_restrictions_v1.py    1550    184    88%
ibm_platform_services/enterprise_billing_units_v1.py       584 …
```
> fix(Usage Reports): re-gen service after recent API changes

- examples/test_iam_policy_management_v1_examples.py
- ibm_platform_services/iam_policy_management_v1.py
- test/integration/test_iam_policy_management_v1.py
- test/unit/test_iam_policy_management_v1.py
Authorization policy type support for enterprise accounts
issue: https://github.ibm.com/IAM/AM-issues/issues/2350
test results:
example:
```
get_v2_assignment_policy() result:
{
"id": "032661b9-ac63-4972-ad28-52909db77844",
"type": "authorization",
"subject": {
"attributes": [
{
"value": "compliance",
"operator": "stringEquals",
"key": "serviceName"
},
{
"value": "0ddc8e9eb0894383b48791ff4ba0b80e",
"operator": "stringEquals",
"key": "accountId"
}
]
},
"resource": {
"attributes": [
{
"value": "appid",
"operator": "stringEquals",
"key": "serviceName"
},
{
"value": "0ddc8e9eb0894383b48791ff4ba0b80e",
"operator": "stringEquals",
"key": "accountId"
}
]
},
"control": {
"grant": {
"roles": [
{
"role_id": …
```
> fix(IAM Policy Management): S2S support for enterprise accounts

- requirements.txt
- setup.py
This commit removes an unused `setuptools` import from the `setup.py`
file. More details about the `setuptools` mess can be found in the following
PR: https://github.com/IBM/python-sdk-core/pull/203 
> fix: remove unused setuptools import

- examples/test_iam_identity_v1_examples.py
- ibm_platform_services/iam_identity_v1.py
- test/integration/test_iam_identity_v1.py
- test/unit/test_iam_identity_v1.py
> feat(IAM Identity): adding Identity Preference API

- examples/test_global_catalog_v1_examples.py
- ibm_platform_services/global_catalog_v1.py
- test/integration/test_global_catalog_v1.py
- test/unit/test_global_catalog_v1.py
Regen after api definition fixes like Price to price, include url field for object update, and support deployment_region query param
Fixes object update and price field syntax
Integration tests
```
python3 -m pytest test/integration/test_global_catalog_v1.py
27 passed, 15 warnings in 16.83s
```
Example tests
```
python3 -m pytest examples/test_global_catalog_v1_examples.py
15 passed, 1 warning in 3.89s
```
> fix(Global Catalog): fix price field capitalization

- examples/test_iam_policy_management_v1_examples.py
- ibm_platform_services/iam_policy_management_v1.py
- test/integration/test_iam_policy_management_v1.py
- test/unit/test_iam_policy_management_v1.py
Adds new Access Management Account Settings API (GET and PATCH paths)
Issue: https://github.ibm.com/IAM/AM-issues/issues/3316
Examples and Integration Test results:
```sh
(venv) kelum@kelums-mbp platform-services-python-sdk % python -m pytest examples/test_iam_policy_management_v1_examples.py
=============================================================================================================== test session starts ===============================================================================================================
platform darwin -- Python 3.9.6, pytest-7.4.4, pluggy-1.5.0
rootdir: /Users/kelum/MyDocuments/Projects/platform-services-python-sdk
plugins: cov-4.1.0
collected 33 items …
```
> feat(IAM Policy Management): add access management account settings API

- examples/test_iam_identity_v1_examples.py
- ibm_platform_services/iam_identity_v1.py
- test/integration/test_iam_identity_v1.py
- test/unit/test_iam_identity_v1.py
added filter parameter to the search api e.g. list apikeys, list serviceid, and list trusted profile
```test\integration\test_iam_identity_v1.py .................................................................................................                                                                [100%]
=============================================================================================== warnings summary ===============================================================================================
test/integration/test_iam_identity_v1.py: 17 warnings
================================================================================= 97 passed, 17 warnings in 705.53s (0:11:45) …
```
> feat(IAM Identity): add filter parameter for search api

- examples/test_iam_policy_management_v1_examples.py
- ibm_platform_services/iam_policy_management_v1.py
- test/integration/test_iam_policy_management_v1.py
- test/unit/test_iam_policy_management_v1.py
Issue: https://github.ibm.com/IAM/AM-issues/issues/3395
> feat(IAM Policy Management): add support for action control templates from IAM

- examples/test_global_tagging_v1_examples.py
- ibm_platform_services/global_tagging_v1.py
- test/integration/test_global_tagging_v1.py
- test/unit/test_global_tagging_v1.py
Added new body parameter to attach/detach tags apis
ITs:
> feat(Global Tagging): regenerate service with latest API definition

- examples/test_iam_identity_v1_examples.py
- ibm_platform_services/iam_identity_v1.py
- test/integration/test_iam_identity_v1.py
- test/unit/test_iam_identity_v1.py
delete trusted profile link with parameters api
```
test\integration\test_iam_identity_v1.py ............................... [ 30%]
........................................................................ [100%]
============================== warnings summary ===============================
test/integration/test_iam_identity_v1.py: 17 warnings
C:\Users\SomanathChavan\AppData\Roaming\Python\Python313\site-packages\ibm_cloud_sdk_core\api_exception.py:56: DeprecationWarning: Using the `code` attribute on the `ApiException` is deprecated and will be removed in the future. Use `status_code` instead.
warnings.warn(
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================ 103 passed, 17 warnings …
```
> fix(IAM Identity): add delete link with parameter api

- examples/test_iam_identity_v1_examples.py
- ibm_platform_services/iam_identity_v1.py
- test/integration/test_iam_identity_v1.py
- test/unit/test_iam_identity_v1.py
Main change -> added two new attributes (`restrict_user_list_visibility` and `restrict_user_domains`) into the Account Settings APIs, all other changes are a result of some rejigging of our API docs to reduce duplication.
Examples
Integration
> feat(IAM Identity): add new account settings
